### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by pramodraja** [UltimateAngular/angular-pro-app-seed#14]
I downloaded code from master branch and when I run yarn install I am getting following error.

PS C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase> yarn install
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > karma-webpack@2.0.3" has incorrect peer dependency "webpack@^1.1.0 || ^2 || ^2.1.0-beta.0 || ^2.2.0-rc.0".
warning " > webpack-dev-server@2.5.0" has incorrect peer dependency "webpack@^2.2.0".
[4/4] Building fresh packages...
[-/2] ⠄ waiting...
error C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.6.2
gyp info using node@12.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError ' +
gyp verb `which` failed     '(C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F ' +
gyp verb `which` failed     '(C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E ' +
gyp verb `which` failed     '(C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError ' +
gyp verb `which` failed     '(C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F ' +
gyp verb `which` failed     '(C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E ' +
gyp verb `which` failed     '(C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:165:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Pramod\\Dev\\ng\\angular-pro-app-seed-01-firebase\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Pramod\Dev\ng\angular-pro-app-seed-01-firebase\node_modules\node-sass
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1

**Comment by EnricoMassoneDeltatre** [comment]
@pramodraja did you managed to solve this ? I have similar problems on windows

**Comment by groninge01** [comment]
#24 will fix this error. Otherwise you can just update the version in the package.json.
